window.JINGLES=[
  "AlbaFrancia FM - Cherche le son.mp3",
  "AlbaFrancia FM - Grave et Girl.mp3",
  "AlbaFrancia FM - Le meilleur du son francais.mp3",
  "AlbaFrancia FM - Radioja (1).mp3",
  "AlbaFrancia FM - Radioja.mp3",
  "AlbaFrancia FM - bonjour ALbanie.mp3",
  "AlbaFrancia FM - clap clap.mp3",
  "AlbaFrancia FM - moins grave girl.mp3",
  "AlbaFrancia FM - musica hispanique.mp3",
  "AlbaFrancia FM - musica.mp3",
  "AlbaFrancia FM - oriental.mp3",
  "AlbaFrancia FM - pa problem.mp3",
  "AlbaFrancia FM culture(1).mp3",
  "AlbaFrancia FM culture.mp3",
  "AlbaFrancia FM la france a tirana (1).mp3",
  "AlbaFrancia FM la france a tirana.mp3",
  "AlbaFrancia Francese (1).mp3",
  "AlbaFrancia Francese.mp3",
  "Croissant Scratch.mp3",
  "La Francia en Albaniaaa Girl.mp3",
  "La Francia en Albaniaaaaaaaaaa Girl.mp3",
  "Parisi în Tirană - Abuse.mp3",
  "Shijoni Rrugën (1).mp3",
  "Shijoni Rrugën.mp3"
];
